import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";
import UserProvider from "./context/UserContext";

import { I18nextProvider, initReactI18next } from "react-i18next";
import i18n from "i18next";
const DETECTION_OPTIONS = {
  order: ["localStorage", "navigator"],
  caches: ["localStorage"],
};

i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        totalEarnings: "Total Earnings",
        totalOrders: "Total Orders",
        totalIncome: "Total Income",
        totalExpenses: "Total Expenses",
        dashboard: "Dashboard",
        bookings: "Bookings",
        hotels: "Hotels",
        rooms: "Rooms",
        settings: "Settings",
        popularRooms: "Popular Rooms",
        search: "Search",
        profile: "Profile",
        myAccount: "My Account",
        logout: "Logout",
        addNewBooking: "Add New Booking",
        createNewBooking: "Create New Booking",
        customerFirstName: "Customer First Name",
        customerLastName: "Customer Last Name",
        customerPhoneNumber: "Customer Phone Number",
        customerEmail: "Customer Email",
        selectClinic: "Select Clinic",
        adults: "Adults",
        children: "Children",
        price: "Price",
        picture: "Picture",
        name: "Name",
        address: "Address",
        rowsPerPage: "Rows per page",
        bed: "Bed",
        id: "ID",
        size: "Size",
        action: "Action",
        addHotel: "Add Hotel",
        addRoom: "Add Room",
        personalDetails: "Personal Details",
        changePassword: "Change Password",
        details: "Details",
        fullName: "Full Name",
        firstName: "First Name",
        zipCode: "Zip Code",
        website: "Website",
        selectPlace: "Select Place",
        newAveragePrice: "New Average Price",
        oldAveragePrice: "Old Average Price",
        facilities: "Facilities",
        cannabisFacilities: "Cannabis Facilities",
        importantInformation: "Important Information",
        selectMainImage: "Select Main Image",
        photos: "Photos",
        selectFile: "Select File",
        create: "Create",
        bedNumber: "Bed Number",
        breakfast: "Breakfast",
        included: "Included",
        notIncluded: "Not Included",
        payment: "Payment",
        payAtPropertyL: "Pay At Property",
        payInAdvance: "Pay In Advance",
        bedRoomSize: "Bedroom Size (in m²)",
        extraDetails: "Extra Details",
        selectPhotos: "Select Photos",
        singleBed: "Single Bed",
        doubleBed: "Double Bed",
        extraLargeDoubleBed: "Extra Large Double Bed",
        queenSizeBed: "Queen Size Bed",
        kingSingleBed: "King Single Bed",
        superKingBed: "Super King Bed",
        email: "Email",
        password: "Password",
        login: "Login",
        dontHaveAccount: "Don't have an account?",
        register: "Register",
        bookingDetails: "Booking Details",
        checkInDate: "Check-In Date",
        checkOutDate: "Check-Out Date",
        cancel: "Cancel",
        delete: "Delete",
        update: "Update",
        hotelsNotFound: "Hotels Not Found",
        add: "Add",
        hotel: "Hotel",
        goBack: "Go Back",
        refundable: "Refundable",
        aboutMe: "About Me",
        personalInformation: "Personal Information",
        contactInformation: "Contact Information",
        userType: "User Type",
        bio: "Bio",
        profileUrl: "Profile URL",
        superAdmin: "Super Admin",
        admin: "Admin",
        manager: "Manager",
        user: "User",
        contactPhone: "Contact Phone",
        location: "Location",
        generalSettings: "General Settings",
        userName: "User Name",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        updating: "Updating...",
        displayName: "Display Name",
        doHaveAccount: "Do you have an account?",
        totalVisitors: "Total Visitors",
        clinics: "Clinics",
        popularProducts: "Popular Products",
        yourListing: "Your Listing",
        addClinic: "Add Clinic",
        featuredImage: "Featured Image",
        city: "City",
        areYouSure: "Are you sure?",
        youWontBeAbleToRevert: "You won't be able to revert this!",
        yesDeleteIt: "Yes, delete it!",
        clinicsNotFound: "Clinics Not Found!",
        deleted: "Deleted!",
        initialConsultFee: "Initial Consult Fee",
        businessHours: "Business Hours",
        opening: "Opening",
        closing: "Closing",
        generalImages: "General Images",
        services: "Services",
        treatments: "Treatments",
        uploadImages: "Upload Images",
        addAnotherImage: "Add another image",
        businessHourCopied: "Business Hours have been copied to all days.",
        addEvent: "Add Event",
        updateEvent: "Update Event",
        enterYourFirstName: "Enter your first name",
        enterYourLastName: "Enter your last name",
        enterYourEmailAddress: "Enter your email address",
        enterYourPhoneNumber: "Enter your phone number",
        enterYourClinicPlace: "Enter your clinic place",
        confirm: "Confirm",
        submit: "Submit",
        uploadFeaturedImage: "Upload Featured Image",
        clinicsAdminPortal: "Clinics Admin Portal",
        adminLogin: "Admin Login",
        adminRegistration: "Admin Registration",
        fillDetails: "Please fill all the fields",
        registrationSuccessful: "Registration successful! Please login now",
        registrationUnSuccessful: "An error occurred!",
        selectAPlace: "Selecting a place is mandatory!",
        addressReq: "Address is required",
        nameReq: "Name is required",
        clinicDeletedSuccessfully: "Clinic deleted successfully",
        clinicCreatedSuccessfully: "Clinic created successfully",
        clinicUpdatedSuccessfully: "Clinic updated successfully",
        switchedTo: "Switched to ",
        logoutSuccessfully: "Logged out successfully",
        emailPassword: "Please enter email and password",
        yourClinics: "Your Clinics",
        submitted: "Submitted!",
        yourFileHasBeenSubmitted: "Your clinic has been created.",
        yourFileHasBeenDeleted: "Your clinic has been deleted.",
        personalDetailsUpdated:
          "Your personal details have been updated successfully!",
        updated: "Updated",
        accountDetailsUpdated:
          "Your account details have been updated successfully!",
        incorrectPassword: "Current password is incorrect",
        passwordUpdated: "Password updated successfully",
        passwordUpdateFailed: "Failed to update password",
        newAndOldPassword: "New Password and Confirm Password must be same",
        whatsYourBusiness: "Hi, what's your business?",
        chooseTheNecessaryFields: "Choose the necessary field of activity",
        continueWithHotelAdmin: "Continue as a hotel admin",
        continueWithClinicAdmin: "Continue as a clinic admin",
        prescriptions: "Prescriptions",
        newClinic: "New Clinic",
        searchClinic: "Search Clinic",
        firstNameReq: "First Name is required",
        lastNameReq: "Last Name is required",
        phoneNumberReq: "Phone Number is required",
        emailReq: "Email is required",
        selectClinicReq: "Clinic is required",
        checkInDateReq: "Check-In Date is required",
        checkInTimeReq: "Check-In Time is required",
        newBooking: "New Booking",
        editClinic: "Edit Clinic",
        latestUpdates: "Latest Updates",
        checkOutSection: "Check out the sections that need updating",
        checkForNewRequests: "Check for new requests",
        unfinishedActions: "Unfinished actions",
        logOut: "Log Out",
        logOutOfTheAccount: "Log out of the account",
        areYouSureYouWantToLogOutOfYourAccount:
          "Are you sure you want to log out of your account?",
        clientManagement: "Client Management",
        prescriptionManagement: "Prescriptions Management",
        unProcessedReq: "Unprocessed prescriptions requests",
        patientName: "Patient Name",
        medicineName: "Name of the medicinal",
        dosage: "Dosage",
        date: "Date",
        activePrescriptions: "Active Prescriptions",
        companyReference: "Company Performance",
        rejectedPrescriptions: "Rejected Prescriptions",
        downloadReport: "Download the current month report",
        allPrescriptions: "All prescriptions",
        allClient: "All client",
        addClient: "Add Client",
        quantity: "Quantity",
        diagnosis: "Diagnosis",
        phoneNumber: "Phone Number",
        notes: "Notes",
        prescriptionsManagement: "Prescriptions Management",
        currentRecipe: "Current Recipe",
        pastPrescriptions: "Past Prescriptions",
        newClient: "New Client",
        newPrescription: "New Prescription",
        errorOccurred: "An error occurred",
        clientName: "Client Name",
        age: "Age",
        patientNameRequired: "Patient Name Required",
        patientNameMustBeString: "Patient Name must be a string",
        ageRequired: "Age Required",
        ageMustBeNumber: "Age must be a number",
        diagnosisRequired: "Diagnosis Required",
        diagnosisMustBeString: "Diagnosis must be a string",
        emailRequired: "Email Required",
        emailMustBeValid: "Email must be a valid",
        phoneNumberRequired: "Phone number required",
        phoneNumberMustBeValid: "Phone number must be a valid",
        addressRequired: "Address Required",
        addressMustBeString: "Address must be a string",
        notesRequired: "Notes Required",
        notesMustBeString: "Notes must be a string",
      },
    },
    th: {
      translation: {
        totalEarnings: "รายได้รวม",
        totalOrders: "คำสั่งซื้อทั้งหมด",
        totalIncome: "รายได้ทั้งหมด",
        totalExpenses: "ค่าใช้จ่ายทั้งหมด",
        dashboard: "แผงควบคุม",
        bookings: "การจอง",
        hotels: "โรงแรม",
        rooms: "ห้องพัก",
        settings: "การตั้งค่า",
        popularRooms: "ห้องพักยอดนิยม",
        search: "ค้นหา",
        profile: "โปรไฟล์",
        myAccount: "บัญชีของฉัน",
        logout: "ออกจากระบบ",
        addNewBooking: "เพิ่มการจองใหม่",
        createNewBooking: "สร้างการจองใหม่",
        customerFirstName: "ชื่อจริงของลูกค้า",
        customerLastName: "นามสกุลของลูกค้า",
        customerPhoneNumber: "หมายเลขโทรศัพท์ของลูกค้า",
        customerEmail: "อีเมลของลูกค้า",
        selectClinic: "เลือกคลีนิค",
        adults: "ผู้ใหญ่",
        children: "เด็ก",
        price: "ราคา",
        picture: "รูปภาพ",
        name: "ชื่อ",
        address: "ที่อยู่",
        rowsPerPage: "แถวต่อหน้า",
        bed: "เตียง",
        id: "รหัส",
        size: "ขนาด",
        action: "การกระทำ",
        addHotel: "เพิ่มโรงแรม",
        addRoom: "เพิ่มห้องพัก",
        personalDetails: "รายละเอียดส่วนบุคคล",
        changePassword: "เปลี่ยนรหัสผ่าน",
        details: "รายละเอียด",
        fullName: "ชื่อเต็ม",
        firstName: "ชื่อจริง",
        zipCode: "รหัสไปรษณีย์",
        website: "เว็บไซต์",
        selectPlace: "เลือกสถานที่",
        newAveragePrice: "ราคาเฉลี่ยใหม่",
        oldAveragePrice: "ราคาเฉลี่ยเก่า",
        facilities: "สิ่งอำนวยความสะดวก",
        cannabisFacilities: "สิ่งอำนวยความสะดวกที่มีกัญชา",
        importantInformation: "ข้อมูลสำคัญ",
        selectMainImage: "เลือกภาพหลัก",
        photos: "รูปภาพ",
        selectFile: "เลือกไฟล์",
        create: "สร้าง",
        bedNumber: "จำนวนเตียง",
        breakfast: "อาหารเช้า",
        included: "รวมอยู่ด้วย",
        notIncluded: "ไม่รวมอยู่ด้วย",
        payment: "การชำระเงิน",
        payAtPropertyL: "จ่ายที่ทรัพย์สิน",
        payInAdvance: "จ่ายล่วงหน้า",
        bedRoomSize: "ขนาดห้องนอน (ตร.ม.)",
        extraDetails: "รายละเอียดเพิ่มเติม",
        selectPhotos: "เลือกภาพ",
        singleBed: "เตียงเดี่ยว",
        doubleBed: "เตียงคู่",
        extraLargeDoubleBed: "เตียงคู่ขนาดใหญ่พิเศษ",
        queenSizeBed: "เตียงควีนไซส์",
        kingSingleBed: "เตียงคิงไซส์เดี่ยว",
        superKingBed: "เตียงซูเปอร์คิงไซส์",
        email: "อีเมล",
        password: "รหัสผ่าน",
        login: "เข้าสู่ระบบ",
        dontHaveAccount: "ยังไม่มีบัญชี?",
        register: "ลงทะเบียน",
        bookingDetails: "รายละเอียดการจอง",
        checkInDate: "วันที่เช็คอิน",
        checkOutDate: "วันที่เช็คเอาท์",
        cancel: "ยกเลิก",
        delete: "ลบ",
        update: "อัปเดต",
        hotelsNotFound: "ไม่พบโรงแรม",
        add: "เพิ่ม",
        hotel: "โรงแรม",
        goBack: "กลับไป",
        refundable: "คืนเงินได้",
        aboutMe: "เกี่ยวกับฉัน",
        personalInformation: "ข้อมูลส่วนตัว",
        contactInformation: "ข้อมูลการติดต่อ",
        userType: "ประเภทผู้ใช้",
        bio: "ประวัติย่อ",
        profileUrl: "URL โปรไฟล์",
        superAdmin: "ผู้ดูแลระบบระดับสูง",
        admin: "ผู้ดูแลระบบ",
        manager: "ผู้จัดการ",
        user: "ผู้ใช้",
        contactPhone: "โทรศัพท์ติดต่อ",
        location: "สถานที่ตั้ง",
        generalSettings: "การตั้งค่าทั่วไป",
        userName: "ชื่อผู้ใช้",
        currentPassword: "รหัสผ่านปัจจุบัน",
        newPassword: "รหัสผ่านใหม่",
        confirmPassword: "ยืนยันรหัสผ่าน",
        updating: "กำลังอัปเดต...",
        displayName: "ชื่อที่แสดง",
        doHaveAccount: "คุณมีบัญชีอยู่หรือไม่?",
        totalVisitors: "ผู้เข้าชมทั้งหมด",
        clinics: "คลีนิค",
        popularProducts: "ผลิตภัณฑ์ยอดนิยม",
        yourListing: "รายการของคุณ",
        addClinic: "เพิ่มคลีนิค",
        featuredImage: "ภาพเด่น",
        city: "เมือง",
        areYouSure: "คุณแน่ใจหรือไม่?",
        youWontBeAbleToRevert: "คุณจะไม่สามารถย้อนกลับได้!",
        yesDeleteIt: "ใช่, ลบมัน!",
        clinicsNotFound: "ไม่พบคลีนิค!",
        deleted: "ลบ!",
        initialConsultFee: "ค่าปรึกษาเริ่มต้น",
        businessHours: "ชั่วโมงทำการ",
        opening: "เปิด",
        closing: "ปิด",
        generalImages: "ภาพทั่วไป",
        services: "บริการ",
        treatments: "การรักษา",
        uploadImages: "อัปโหลดภาพ",
        addAnotherImage: "เพิ่มภาพอีกภาพ",
        businessHourCopied: "ชั่วโมงทำการได้ถูกคัดลอกไปยังทุกวันแล้ว",
        addEvent: "เพิ่มกิจกรรม",
        updateEvent: "อัปเดตกิจกรรม",
        enterYourFirstName: "ป้อนชื่อจริงของคุณ",
        enterYourLastName: "ป้อนนามสกุลของคุณ",
        enterYourEmailAddress: "ป้อนที่อยู่อีเมลของคุณ",
        enterYourPhoneNumber: "ป้อนหมายเลขโทรศัพท์ของคุณ",
        enterYourClinicPlace: "ป้อนสถานที่คลีนิคของคุณ",
        confirm: "ยืนยัน",
        submit: "ส่ง",
        uploadFeaturedImage: "อัปโหลดภาพเด่น",
        clinicsAdminPortal: "พอร์ทัลผู้ดูแลคลีนิค",
        adminLogin: "เข้าสู่ระบบผู้ดูแลระบบ",
        adminRegistration: "ลงทะเบียนผู้ดูแลระบบ",
        fillDetails: "กรุณากรอกข้อมูลทั้งหมด",
        registrationSuccessful: "ลงทะเบียนสำเร็จ! กรุณาเข้าสู่ระบบตอนนี้",
        registrationUnSuccessful: "เกิดข้อผิดพลาด!",
        selectAPlace: "การเลือกสถานที่เป็นสิ่งจำเป็น!",
        addressReq: "จำเป็นต้องมีที่อยู่",
        nameReq: "จำเป็นต้องมีชื่อ",
        clinicDeletedSuccessfully: "ลบคลีนิคเรียบร้อยแล้ว",
        clinicCreatedSuccessfully: "สร้างคลีนิคเรียบร้อยแล้ว",
        clinicUpdatedSuccessfully: "อัปเดตคลีนิคเรียบร้อยแล้ว",
        switchedTo: "สลับเป็น ",
        logoutSuccessfully: "ออกจากระบบเรียบร้อยแล้ว",
        emailPassword: "กรุณากรอกอีเมลและรหัสผ่าน",
        yourClinics: "คลีนิคของคุณ",
        submitted: "ส่งแล้ว!",
        yourFileHasBeenSubmitted: "คลีนิคของคุณได้ถูกสร้างแล้ว",
        yourFileHasBeenDeleted: "คลีนิคของคุณได้ถูกลบแล้ว",
        personalDetailsUpdated: "อัปเดตรายละเอียดส่วนบุคคลของคุณเรียบร้อยแล้ว!",
        updated: "อัปเดตแล้ว",
        accountDetailsUpdated: "อัปเดตรายละเอียดบัญชีของคุณเรียบร้อยแล้ว!",
        incorrectPassword: "รหัสผ่านปัจจุบันไม่ถูกต้อง",
        passwordUpdated: "อัปเดตรหัสผ่านเรียบร้อยแล้ว",
        passwordUpdateFailed: "การอัปเดตรหัสผ่านล้มเหลว",
        newAndOldPassword: "รหัสผ่านใหม่และยืนยันรหัสผ่านต้องเหมือนกัน",
        whatsYourBusiness: "สวัสดี, ธุรกิจของคุณคืออะไร?",
        chooseTheNecessaryFields: "เลือกเขตข้อมูลที่จำเป็น",
        continueWithHotelAdmin: "ดำเนินการต่อในฐานะผู้ดูแลโรงแรม",
        continueWithClinicAdmin: "ดำเนินการต่อในฐานะผู้ดูแลคลีนิค",
        prescriptions: "ใบสั่งยา",
        newClinic: "คลีนิคใหม่",
        searchClinic: "ค้นหาคลีนิค",
        firstNameReq: "จำเป็นต้องมีชื่อจริง",
        lastNameReq: "จำเป็นต้องมีนามสกุล",
        phoneNumberReq: "จำเป็นต้องมีหมายเลขโทรศัพท์",
        emailReq: "จำเป็นต้องมีอีเมล",
        selectClinicReq: "จำเป็นต้องเลือกคลีนิค",
        checkInDateReq: "จำเป็นต้องมีวันที่เช็คอิน",
        checkInTimeReq: "จำเป็นต้องมีเวลาที่เช็คอิน",
        newBooking: "การจองใหม่",
        editClinic: "แก้ไขคลีนิค",
        latestUpdates: "อัปเดตล่าสุด",
        checkOutSection: "ตรวจสอบส่วนที่ต้องอัปเดต",
        checkForNewRequests: "ตรวจสอบคำขอใหม่",
        unfinishedActions: "การกระทำที่ยังไม่เสร็จ",
        recipes: "สูตรยา",
        logOut: "ออกจากระบบ",
        logOutOfTheAccount: "ออกจากระบบบัญชี",
        areYouSureYouWantToLogOutOfYourAccount:
          "คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบบัญชีของคุณ?",
        clientManagement: "การจัดการลูกค้า",
        prescriptionManagement: "การจัดการใบสั่งยา",
        unProcessedReq: "คำขอใบสั่งยาที่ยังไม่ดำเนินการ",
        patientName: "ชื่อผู้ป่วย",
        medicineName: "ชื่อยาที่ใช้",
        dosage: "ปริมาณยา",
        date: "วันที่",
        activeRecipes: "สูตรยาที่ใช้งานอยู่",
        companyReference: "ประสิทธิภาพบริษัท",
        rejectedRecipes: "สูตรยาที่ถูกปฏิเสธ",
        downloadReport: "ดาวน์โหลดรายงานเดือนปัจจุบัน",
        allPrescriptions: "ใบสั่งยาทั้งหมด",
        allClient: "ลูกค้าทั้งหมด",
        addClient: "เพิ่มลูกค้า",
        quantity: "ปริมาณ",
        diagnosis: "การวินิจฉัย",
        phoneNumber: "หมายเลขโทรศัพท์",
        notes: "บันทึก",
        prescriptionsManagement: "การจัดการใบสั่งยา",
        currentRecipe: "สูตรยาปัจจุบัน",
        pastPrescriptions: "ใบสั่งยาในอดีต",
        newClient: "ลูกค้าใหม่",
        newPrescription: "ใบสั่งยาใหม่",
        errorOccurred: "เกิดข้อผิดพลาด",
        clientName: "ชื่อลูกค้า",
        age: "อายุ",
        patientNameRequired: "จำเป็นต้องมีชื่อผู้ป่วย",
        patientNameMustBeString: "ชื่อผู้ป่วยต้องเป็นข้อความ",
        ageRequired: "จำเป็นต้องมีอายุ",
        ageMustBeNumber: "อายุต้องเป็นตัวเลข",
        diagnosisRequired: "จำเป็นต้องมีการวินิจฉัย",
        diagnosisMustBeString: "การวินิจฉัยต้องเป็นข้อความ",
        emailRequired: "จำเป็นต้องมีอีเมล",
        emailMustBeValid: "อีเมลต้องถูกต้อง",
        phoneNumberRequired: "จำเป็นต้องมีหมายเลขโทรศัพท์",
        phoneNumberMustBeValid: "หมายเลขโทรศัพท์ต้องถูกต้อง",
        addressRequired: "จำเป็นต้องมีที่อยู่",
        addressMustBeString: "ที่อยู่ต้องเป็นข้อความ",
        notesRequired: "จำเป็นต้องมีบันทึก",
        notesMustBeString: "บันทึกต้องเป็นข้อความ",
      },
    },
  },
  detection: DETECTION_OPTIONS,
  lng: localStorage.getItem("SelectedLanguage") || "en",
  fallbackLng: "en",
  interpolation: { escapeValue: false },
});

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <UserProvider>
      <I18nextProvider i18n={i18n}>
        <App />
      </I18nextProvider>
    </UserProvider>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
